version: '3.2'
services:
    msaude-integ:
        build:
            context: .
            dockerfile: Dockerfile.integ
            args:
               jar_file: msaude-integ/target/*.jar 
        container_name: msaude-integ
        ports:
            - "8080:8080"
        networks:
            - network 
            - account-manager_network
            - consultation_network
        depends_on: 
            - "msaudedb"
        volumes: 
          - type: bind
            source: /opt/msaude/data
            target: /opt/msaude/data
        restart: unless-stopped

    msaudedb:
        build: 
            context: .
            dockerfile: Dockerfile.db
        container_name: msaudedb
        ports: 
            - "3307:3306"
        networks: 
            - network
        volumes:
            - type: volume
              source: dbdata
              target: /opt/msaude/data
        restart: unless-stopped
networks: 
  network:
    driver: bridge
  consultation_network:
    external: true
  account-manager_network:
    external: true

volumes:
  dbdata:
